### ISSUE TITLE
I opened it in google sheets and it got an error

### ISSUE THREAD

**Issue by amozoss** [brentadamson/dataconnector#9] opened 2021-03-26 20:43 UTC
```
react-dom.production.min.js:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=ScriptError%3A%20Authorization%20is%20required%20to%20perform%20that%20action.&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Nc (react-dom.production.min.js:72)
    at react-dom.production.min.js:81
    at T (react-dom.production.min.js:95)
    at zj (react-dom.production.min.js:230)
    at Th (react-dom.production.min.js:152)
    at tj (react-dom.production.min.js:152)
    at Te (react-dom.production.min.js:146)
    at react-dom.production.min.js:61
    at unstable_runWithPriority (react.production.min.js:25)
    at Da (react-dom.production.min.js:60)
Me @ react-dom.production.min.js:125
react-dom.production.min.js:72 Uncaught (in promise) Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=ScriptError%3A%20Authorization%20is%20required%20to%20perform%20that%20action.&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Nc (react-dom.production.min.js:72)
    at react-dom.production.min.js:81
    at T (react-dom.production.min.js:95)
    at zj (react-dom.production.min.js:230)
    at Th (react-dom.production.min.js:152)
    at tj (react-dom.production.min.js:152)
    at Te (react-dom.production.min.js:146)
    at react-dom.production.min.js:61
    at unstable_runWithPriority (react.production.min.js:25)
    at Da (react-dom.production.min.js:60)
    
    ```

**Comment by brentadamson** [comment] 2021-04-19 03:01
Oops, didn't mean to close it. Still need to fix the underlying issue, which is "Error: We're sorry, a server error occurred while reading from storage. Error code PERMISSION_DENIED.".

**Comment by brentadamson** [comment] 2021-04-19 03:21
`Error: We're sorry, a server error occurred while reading from storage. Error code PERMISSION_DENIED.` was solved by fully logging out of Google Sheets in dev mode. It sounds like the cause of yours was some other server-side error, which I'll try to track down.

**Comment by brentadamson** [comment] 2021-04-24 22:04
Should be fixed. Gonna close this. Please reopen if it persists.

**Closed by brentadamson** 2021-04-24 22:04 UTC
